/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * The package version.
 */
export class Version extends SpeakeasyBase {
    @SpeakeasyMetadata()
    version?: string;
}
